app/assets/stylesheets/application.scss
app/views/layouts/application.html.erb

Hey Moz please accept - this will help us make the website visible

commented out bootstrap & stylesheets for now

---

app/controllers/application_controller.rb
db/migrate/20230513160057_add_name_to_users.rb
db/schema.rb

added first/last name to users model and updated application controller

added first/last name to users model and updated application controller

---

Gemfile.lock
app/controllers/application_controller.rb

That's it - I removed an extra end from application_controller :)

Removed extra end from application_controller

---

app/models/item.rb
app/models/user.rb
db/schema.rb

Needed associations for the user model, has_many :items + :bookings

added associations to models

---

app/controllers/items_controller.rb
config/routes.rb
test/controllers/items_controller_test.rb

Added controller for items and the actions for index, show, new, create and destroy

items controller added

---

app/views/items/show.html.erb
db/migrate/20230516191839_remove_seller_id_from_items.rb
db/schema.rb

fixed schema

---

db/migrate/20230516191839_remove_seller_id_from_items.rb
db/seeds.rb

fixed seed

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_item_card.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/items_controller.rb
app/controllers/pages_controller.rb
app/views/layouts/application.html.erb
app/views/pages/_filter_bar.html.erb
app/views/pages/_item_card.html.erb
app/views/pages/home.html.erb
db/schema.rb

- Items listed on homepage in basic grid layout
- Item cards link to item show page
- NEXT UP: Basic filtering functionality on homepage, DEPENDENT ON: more seeded items.

Basic homepage

---

db/seeds.rb

Switched Booking.create seeds to show item 1 first and item 2 second

---

app/controllers/bookings_controller.rb
app/controllers/items_controller.rb
app/models/item.rb

Can now create an item and it displays on the home page

create function working

---

app/views/layouts/application.html.erb
app/views/pages/home.html.erb

sign in/ sign out added

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_category_bar.scss
app/controllers/pages_controller.rb
app/views/bookings/show.html.erb
app/views/items/new.html.erb
app/views/items/show.html.erb
app/views/pages/_category_bar.html.erb
app/views/pages/home.html.erb
db/migrate/20230518185428_add_category_to_items.rb
db/schema.rb
db/seeds.rb

No real styling yet, but happy to get this working:
- Category was added to the items model.
- Categories are defined in the pages controller and iterated over to populate the view.
- Clicking a category link does not redirect, instead the items on the homepage are filtered to show only those that match the selected category.
- The ALL category link is a href to the unfiltered homepage.
- I updated the seed file to use a loop (and Faker in places) to generate 21 entries of User, Item and Booking.
- I've displayed the category appear in relevant views.

Homepage category filter functionality

---

db/seeds.rb

We don't need to seed bookings now as we will create them as a user.

Removed seeding bookings

---

app/controllers/application_controller.rb
app/controllers/bookings_controller.rb
app/controllers/items_controller.rb
app/controllers/pages_controller.rb
app/views/items/show.html.erb

added authentications for users, can only book an item if signed in

Authenticate users

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_index.scss
app/views/bookings/show.html.erb
app/views/items/show.html.erb

back to home buttons on items & bookings show pages

back to home buttons on items & bookings show pages

---

app/views/pages/_navbar.html.erb
app/views/pages/home.html.erb

Added navbar partial and link to add new item page.

Added navbar partial

---

app/views/pages/_navbar.html.erb
app/views/pages/home.html.erb

Added link to add new items to navbar.

Added link to aadd new item

---

app/controllers/bookings_controller.rb
app/views/items/show.html.erb

- Changed book item link to post request
- Updated bookings controller create method to assign a booking to the logged in user

Actually create bookings

---

app/views/bookings/show.html.erb
app/views/devise/registrations/new.html.erb

User name displays on booking confirmation

User name added to booking confirmation

---

app/views/items/new.html.erb

List a new item back to home page solve

List a new item back to home page solve

---

app/controllers/bookings_controller.rb
app/views/bookings/index.html.erb
config/routes.rb

A user is now able to see their specific bookings

bookings index created

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_item_card.scss
app/controllers/items_controller.rb
app/models/item.rb
app/views/items/new.html.erb
app/views/items/show.html.erb
app/views/pages/_item_card.html.erb
config/environments/development.rb
config/storage.yml
db/migrate/20230520140526_create_active_storage_tables.active_storage.rb
db/schema.rb

This pull request is about integrating the Cloudinary gem into the app to handle image processing and storage. I've also updated the Item model, show page, and new item form to accommodate and display images. Lastly, images of items are now visible on the homepage. If an item does not have an image, a blank space is left instead.

Images attached to items

---

app/views/pages/_navbar.html.erb

Add link to home page to all bookings page.

link to all bookings page added

---

app/views/pages/_navbar.html.erb

Updated the order of links in nav

changed order of links

---

app/controllers/items_controller.rb
app/models/item.rb

Added category to permitted params, and to item model validation

---

Gemfile
Gemfile.lock
app/controllers/items_controller.rb
app/controllers/pages_controller.rb
app/javascript/controllers/index.js
app/javascript/controllers/map_controller.js
app/models/item.rb
app/views/items/index.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
config/application.rb
config/initializers/geocoder.rb
config/routes.rb
db/migrate/20230523190546_add_coordinates_to_items.rb
db/migrate/20230523191125_add_address_to_items.rb
db/schema.rb
db/seeds.rb

Geocoder map addition 
Markers working
Item details & image need to be added
Need to add within the seeding process the addition of addresses too

Bookings show

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_header_and_navbar.scss
app/assets/stylesheets/components/_item_card.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/_header_and_navbar.html.erb
app/views/pages/_navbar.html.erb

Still working on this 
Font changes, item card styling
Removed welcome message temporarily to revert issue

More homepage styling

---

app/views/bookings/index.html.erb

added photos to the  bookings index page

added photos to bookings index

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_showpagecard.scss
app/views/items/show.html.erb
app/views/pages/_header_and_navbar.html.erb

Show page styling
